- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: fourth-tiger-319208
      gcp_auth_kind: serviceaccount
      gcp_cred_file: my_acc.json
      zone: "asia-southeast1-b"
      region: "asia-southeast1"

  tasks:
    - name: create a disk for webserver1
      gcp_compute_disk:
          name: 'disk-instance-1'
          size_gb: 30
          source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts'
          zone: "{{ zone }}"
          project: "{{ gcp_project }}"
          auth_kind: "{{ gcp_auth_kind }}"
          service_account_file: "{{ gcp_cred_file }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      register: disk1

    - name: create IP1
      gcp_compute_address:
          name: 'address-instance-1'
          region: "{{ region }}"
          project: "{{ gcp_project }}"
          auth_kind: "{{ gcp_auth_kind }}"
          service_account_file: "{{ gcp_cred_file }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      register: IP1

    - name: creat instance one
      gcp_compute_instance:
          state: present
          name: web-server-1
          machine_type: e2-medium
          disks:
            - auto_delete: true
              boot: true
              disk_encryption_key:
                raw_key: 'QW5zJGlCMWVQdw=='
              source: "{{ disk1 }}"
          network_interfaces:
            - network: null
              access_configs:
                - name: 'External NAT'
                  nat_ip: "{{ IP1 }}"
                  type: 'ONE_TO_ONE_NAT'
          zone: "{{ zone }}"
          project: "{{ gcp_project }}"
          auth_kind: "{{ gcp_auth_kind }}"
          service_account_file: "{{ gcp_cred_file }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      register: instance

    - name: create a disk for webserver2
      gcp_compute_disk:
          name: 'disk-instance-2'
          size_gb: 30
          source_image: 'projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts'
          zone: "{{ zone }}"
          project: "{{ gcp_project }}"
          auth_kind: "{{ gcp_auth_kind }}"
          service_account_file: "{{ gcp_cred_file }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      register: disk2
  
    - name: create IP2
      gcp_compute_address:
          name: 'address-instance-2'
          region: "{{ region }}"
          project: "{{ gcp_project }}"
          auth_kind: "{{ gcp_auth_kind }}"
          service_account_file: "{{ gcp_cred_file }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      register: IP2
  
    - name: creat instance two
      gcp_compute_instance:
          state: present
          name: web-server-2
          machine_type: e2-medium
          disks:
            - auto_delete: true
              boot: true
              disk_encryption_key:
                raw_key: 'QW5zJGlCMWVQdw=='
              source: "{{ disk2 }}"
          network_interfaces:
            - network: null
              access_configs:
                - name: 'External NAT'
                  nat_ip: "{{ IP2 }}"
                  type: 'ONE_TO_ONE_NAT'
          zone: "{{ zone }}"
          project: "{{ gcp_project }}"
          auth_kind: "{{ gcp_auth_kind }}"
          service_account_file: "{{ gcp_cred_file }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      register: instance
